# Generated by Django 5.2.3 on 2025-07-01 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_alfabeta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('precio_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monodroga',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('medicamento_alfabeta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorio'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='monodroga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.monodroga'),
        ),
    ]
