# Generated by Django 5.2.3 on 2025-07-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecio',
            name='precio_caja',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='historialprecio',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
