# Generated by Django 5.2.3 on 2025-07-02 01:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_historialprecio_precio_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='cantidad',
            field=models.IntegerField(blank=True, help_text='Unidades por caja', null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=16),
        ),
    ]
